Repository BitteProtocol/make-agent, pull requests merged in 2024-10, with the labels that each got.

#2 Retry for fetching API spec
  src/services/openapi-service.ts
  src/services/tunnel-service.ts
  src/utils/url-utils.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#3 Minor fixes
  src/commands/delete.ts
  src/commands/register.ts
  src/commands/update.ts
  src/services/tunnel-service.ts
Labels: enhancement, Other, Review effort [1-5]: 2

#4 removes localtunnel and adds ngrok
  bun.lockb
  package.json
  src/services/tunnel-service.ts
Labels: enhancement, dependencies
